env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - react
rules:
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
